# Hugo configuration file
title: Comind

# https://gohugo.io/host-and-deploy/host-on-github-pages/#step-1
caches:
  images:
    dir: :cacheDir/images

# import hextra as module
module:
  imports:
    - path: github.com/imfing/hextra

markup:
  # allow raw html
  goldmark:
    renderer:
      unsafe: true

  # enable hextra syntax highlight
  highlight:
    noClasses: false

menu:
  main:
    - name: Docs
      pageRef: /docs
      weight: 1
    - name: Blog
      pageRef: /blog
      weight: 3
    - name: GitHub
      weight: 5
      url: "https://github.com/cpfiffer/comind"
      params:
        icon: github
    - name: Bluesky
      weight: 6
      url: "https://bsky.app/profile/cameron.pfiffer.org"
      params:
        icon: bluesky

params:
  navbar:
    displayTitle: false
    displayLogo: true

    logo:
      path: /logo-dark.svg
      dark: /logo-dark.svg
      link: /
      width: 200
      height: 20

  footer:
    displayCopyright: false
    displayPoweredBy: false

  editURL:
    enable: true
    base: "https://github.com/imfing/hextra-starter-template/edit/main/content"
