# Hugo configuration file
title: Comind

# import hextra as module
module:
  imports:
    - path: github.com/imfing/hextra

markup:
  # allow raw html
  goldmark:
    renderer:
      unsafe: true

  # enable hextra syntax highlight
  highlight:
    noClasses: false

menu:
  main:
    - name: Docs
      pageRef: /docs
      weight: 1
    - name: About
      pageRef: /about
      weight: 2
    - name: Blog
      pageRef: /blog
      weight: 3
    - name: GitHub
      weight: 5
      url: "https://github.com/cpfiffer/comind"
      params:
        icon: github
    - name: Bluesky
      weight: 6
      url: "https://bsky.app/profile/cameron.pfiffer.org"
      params:
        icon: bluesky

params:
  navbar:
    displayTitle: true
    displayLogo: false

  footer:
    displayCopyright: false
    displayPoweredBy: false

  editURL:
    enable: true
    base: "https://github.com/imfing/hextra-starter-template/edit/main/content"